### ISSUE TITLE
problem with my css

### ISSUE THREAD

**Issue by Elisa0122** [Elisa0122/web-design-2-independent-project#1]
Hi @wendywarren,

1. This morning we fixed a problem with my CSS code but the problem moved to my other grid (the one where I didn't have any problem). Could you have a look at it, please?
<img width="862" alt="Screen Shot 2022-04-01 at 8 58 19 PM" src="https://user-images.githubusercontent.com/83783101/161360056-ed084434-ba21-4e10-8108-850b4cbf9cf6.png">

2. Also I have issues with contrast accessibility with Markbot, I don't understand why...

3. I created my favicon but markbot didn't recognize it and also ask me for 48px but with X-Icon Editor they don't propose the 48px size and the other link that I have I need to be bought so I prefer to avoid it. Do you know another way to do it?

4. I can't open my page with safari

5. Could we plan a zoom meeting on Monday? 

Regards,

Elisa Nicot

**Comment by wendywarren** [comment]
Hi @Elisa0122,

I took a look this evening and came up with a decent solution to your issue.

I've included screenshots for you to compare with your existing code.

I first removed the `display: grid;`  from the section including the content for visitor parking and garbage & recycling. 

<img width="1668" alt="Screen Shot 2022-04-05 at 9 11 04 PM" src="https://user-images.githubusercontent.com/12865609/161875886-299c3109-6a0e-41b4-9f04-f84b01e51f25.png">



Then I created a div with a class of 'info' that wrapped around the paragraph and card div. That one was set to `display: flex;`. I also gave it a margin-top to create some space between the heading and content. Play around with that spacing.

<img width="1726" alt="Screen Shot 2022-04-05 at 9 05 33 PM" src="https://user-images.githubusercontent.com/12865609/161876080-8acba4db-30a6-41e2-ae65-5c1f9661155e.png">



I set the width for the card to be 25% and changed it's order to be -1 so that it came before the paragraph. You could also just change the html order. I also removed a few properties that weren't doing anything.

<img width="1721" alt="Screen Shot 2022-04-05 at 9 06 38 PM" src="https://user-images.githubusercontent.com/12865609/161876288-ab00122d-e738-4db1-9f38-2bc7c998aa15.png">



Lastly, I set the paragraph to be 75% and set the margin-left to auto so that it would take up the remaining space in the container.

<img width="1722" alt="Screen Shot 2022-04-05 at 9 05 53 PM" src="https://user-images.githubusercontent.com/12865609/161876385-14ac6dc6-21dd-4746-b737-1dda357f139f.png">



Let me know how this goes or if you have any questions. :)

Wendy
